# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/daniel/Ex03

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/daniel/Ex03

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/daniel/Ex03/CMakeFiles /home/daniel/Ex03//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/daniel/Ex03/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named flightsService

# Build rule for target.
flightsService: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 flightsService
.PHONY : flightsService

# fast build rule for target.
flightsService/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flightsService.dir/build.make CMakeFiles/flightsService.dir/build
.PHONY : flightsService/fast

#=============================================================================
# Target rules for targets named Utility

# Build rule for target.
Utility: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Utility
.PHONY : Utility

# fast build rule for target.
Utility/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility.dir/build.make CMakeFiles/Utility.dir/build
.PHONY : Utility/fast

Cpp_files/flightsService.o: Cpp_files/flightsService.cpp.o
.PHONY : Cpp_files/flightsService.o

# target to build an object file
Cpp_files/flightsService.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flightsService.dir/build.make CMakeFiles/flightsService.dir/Cpp_files/flightsService.cpp.o
.PHONY : Cpp_files/flightsService.cpp.o

Cpp_files/flightsService.i: Cpp_files/flightsService.cpp.i
.PHONY : Cpp_files/flightsService.i

# target to preprocess a source file
Cpp_files/flightsService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flightsService.dir/build.make CMakeFiles/flightsService.dir/Cpp_files/flightsService.cpp.i
.PHONY : Cpp_files/flightsService.cpp.i

Cpp_files/flightsService.s: Cpp_files/flightsService.cpp.s
.PHONY : Cpp_files/flightsService.s

# target to generate assembly for a file
Cpp_files/flightsService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flightsService.dir/build.make CMakeFiles/flightsService.dir/Cpp_files/flightsService.cpp.s
.PHONY : Cpp_files/flightsService.cpp.s

Library/libUtility.o: Library/libUtility.cpp.o
.PHONY : Library/libUtility.o

# target to build an object file
Library/libUtility.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility.dir/build.make CMakeFiles/Utility.dir/Library/libUtility.cpp.o
.PHONY : Library/libUtility.cpp.o

Library/libUtility.i: Library/libUtility.cpp.i
.PHONY : Library/libUtility.i

# target to preprocess a source file
Library/libUtility.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility.dir/build.make CMakeFiles/Utility.dir/Library/libUtility.cpp.i
.PHONY : Library/libUtility.cpp.i

Library/libUtility.s: Library/libUtility.cpp.s
.PHONY : Library/libUtility.s

# target to generate assembly for a file
Library/libUtility.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Utility.dir/build.make CMakeFiles/Utility.dir/Library/libUtility.cpp.s
.PHONY : Library/libUtility.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Utility"
	@echo "... flightsService"
	@echo "... Cpp_files/flightsService.o"
	@echo "... Cpp_files/flightsService.i"
	@echo "... Cpp_files/flightsService.s"
	@echo "... Library/libUtility.o"
	@echo "... Library/libUtility.i"
	@echo "... Library/libUtility.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

